### ISSUE TITLE
Make sure camera works on Driver Station

### ISSUE THREAD

**Issue by SagesOfRPG** [newheights/RobotBuilderTest#11]

**Comment by SagesOfRPG** [comment]
https://wpilib.screenstepslive.com/s/4485/m/24194/l/288981-using-the-microsoft-lifecam-hd-3000

Use RoboRio web dashboard to determine camera name

https://wpilib.screenstepslive.com/s/4485/m/24166/l/262266?data-resolve-url=true&data-manual-id=24166

**Comment by FRCTeam5902** [comment]
Camera Works!
