### ISSUE TITLE
Underlined text! With intake joystick command

### ISSUE THREAD

**Issue by FRCTeam5902** [newheights/RobotBuilderTest#12]
This goes in Intake.java, underneath where it says END AUTOGENERATED CODE, SOURCE = ROBOTBUILDER ID = DEFAULT_COMMAND

public void DriverControl(Joystick stick) {
        if (stick.getY() < 0) {
            new IntakeBall();
        }
        if (stick.getY() > 0) {
            new EjectBall();
        }
        if (stick.getY() == 0) {
            new IntakeDoNothing();
        }

**Comment by SagesOfRPG** [comment]
Figured this out. We just needed to map the motor directly to the axis.
