### ISSUE TITLE
Map Joystick forward and back to manual control of the intake motor.

### ISSUE THREAD

**Issue by SagesOfRPG** [newheights/RobotBuilderTest#3]

**Comment by FRCTeam5902** [comment]
https://wpilib.screenstepslive.com/s/3120/m/7912/l/133053-joysticks

**Comment by FRCTeam5902** [comment]
Joystick Explorer Utility Program - http://firstforge.wpi.edu/sf/frs/do/viewRelease/projects.wpilib/frs.joystick_explorer.joystick_explorer

**Comment by SagesOfRPG** [comment]
This is done. Mapped the motor speed to the reading of the y axis direct.
